#!/bin/sh
pyinstaller -p protein_loc_scraper --hidden-import scraper --hidden-import dataframe --onefile protein_loc_scraper/locScraper.py
cd dist
tar -czvf locScraper_Darwin_x64.tar.gz locScraper
cd ..
